# This is a placeholder so actions won't default to a getting started page

name: Placeholder

#on: push
on: 
   schedule:
   - cron: '50 13,14 * * *'


jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

#hello
